quests = {
    "q1": {
        "id": "q1",
        "title": "A Cripta Esquecida",
        "description": "Explore a cripta ao norte e elimine os mortos-vivos que assombram os aldeões.",
        "difficulty": "Fácil",
        "difficulty_color": "green",
        "reward_xp": 300,
        "reward_gold": 50,
        "status": "available",
        "hero_id": None,
        "accepted_at": None,
        "completed_at": None,
        "icon": "💀",
    },
    "q2": {
        "id": "q2",
        "title": "O Grimório Perdido",
        "description": "Encontre o grimório do arquimago Valdris nas ruínas da torre encantada.",
        "difficulty": "Médio",
        "difficulty_color": "yellow",
        "reward_xp": 600,
        "reward_gold": 120,
        "status": "available",
        "hero_id": None,
        "accepted_at": None,
        "completed_at": None,
        "icon": "📖",
    },
    "q3": {
        "id": "q3",
        "title": "Dragão de Gelo de Vorheim",
        "description": "O dragão Vorheim aterroriza o reino. Apenas o mais corajoso pode enfrentá-lo.",
        "difficulty": "Épico",
        "difficulty_color": "red",
        "reward_xp": 2000,
        "reward_gold": 500,
        "status": "available",
        "hero_id": None,
        "accepted_at": None,
        "completed_at": None,
        "icon": "🐉",
    },
    "q4": {
        "id": "q4",
        "title": "Poções para a Aldeia",
        "description": "A aldeia de Mireth precisa de poções de cura. Colete ervas e entregue ao curandeiro.",
        "difficulty": "Fácil",
        "difficulty_color": "green",
        "reward_xp": 150,
        "reward_gold": 30,
        "status": "available",
        "hero_id": None,
        "accepted_at": None,
        "completed_at": None,
        "icon": "🧪",
    },
}
